# Generated by Django 4.1.4 on 2022-12-19 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='ClubId',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Request_id',
            new_name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='login',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
    ]
